version: '3.5'
services:
  app:
    image: my-local/kallithea-rev:36a36ebdf4bb
    build:
      context: ./build
      args:
        - KALLITHEA_REV=36a36ebdf4bb
    command: dumb-init bash /kallithea/assets/patched_startup.sh
    restart: unless-stopped
    ports:
      - "9999:5000"
      - "2222:22"
    volumes:
      - ./data/config:/kallithea/config
      - ./data/repos:/kallithea/repos
      - ./assets:/kallithea/assets
    environment:
      - TZ=Asia/Tokyo
      - KALLITHEA_ADMIN_USER=admin
      - KALLITHEA_ADMIN_PASS=admin123
      - KALLITHEA_ADMIN_MAIL=admin@example.com
      - KALLITHEA_LOCALE=ja_JP.UTF-8
      - KALLITHEA_OVERRIDE_DIR=/kallithea/assets/override
      - KALLITHEA_PATCH_DIR=/kallithea/assets/patches
